language: node_js
node_js:
  - "8.6.0"
  - "node"
env:
  - WEBPACK_VERSION=4
install:
  - if [[ `npm -v` != 5.7* ]]; then npm install -g npm@'>=5.7.1'; fi
  - npm ci
before_script:
  - if [[ -n "$WEBPACK_VERSION" ]]; then npm install --no-save webpack@$WEBPACK_VERSION; fi
stages:
  - lint
  - test:unit
  - build
jobs:
  include:
    - stage: lint
      script:
        # Run linter
        - npm run lint
    - stage: test:unit
      script:
        # Run tests unit
        - npm run test:unit
    - stage: build
      script:
        # Build all
        - npm run build
